
name: build-and-release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxres-dev
        if: matrix.os == 'ubuntu-latest'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: build pherguson
        run: |
          pyinstaller --onefile --name pherguson-${{ runner.os }}-${{ runner.arch }} pherguson.py

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}_build
          path: |
            dist/

  release:
    needs: [build]

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/download-artifact@master
        with:
          name: Linux_build
          path: dist/

      - name: create release
        uses: ncipollo/release-action@v1 # https://github.com/marketplace/actions/create-release
        with:
          token: ${{ secrets.TOKEN }}
          generateReleaseNotes: true
          artifacts: "dist/*"
